name: Tests
on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run linters
        run: poetry run ruff check src tests
      - name: Run tests
        run: poetry run pytest --cov
      - name: "Upload coverage to Codecov"
        if: matrix.python-version == 3.13  # Only upload coverage once per run
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

          token: ${{ secrets.CODECOV_TOKEN }}
